# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.4.0

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-02-15T11:58:33Z"
  labels:
    app: minecraft-pod
  name: minecraft-pod
spec:
  ports:
  - name: "25565"
    nodePort: 32313
    port: 25565
    targetPort: 25565
  selector:
    app: minecraft-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-02-15T11:58:33Z"
  labels:
    app: minecraft-pod
  name: minecraft-pod
spec:
  containers:
  - args:
    - TYPE=FABRIC
    - VERSION=1.20.1
    env:
    - name: EULA
      value: "TRUE"
    image: docker.io/itzg/minecraft-server:latest
    name: minecraft
    ports:
    - containerPort: 25565
    volumeMounts:
    - mountPath: /data
      name: home-ulf-minecraft-server-host-0
  volumes:
  - hostPath:
      path: /home/ulf/minecraft-server
      type: Directory
    name: home-ulf-minecraft-server-host-0

